### ISSUE TITLE
Support secure spaces

### ISSUE THREAD

**Issue by kevromster** [anticrm/platform#112]
As a user, I want to make "private" spaces with restricted access to all documents inside, so that only a certain set of people have access to such spaces.
- [ ] Implement map what spaces the user is included in (on backend)
- [x] Restrict server answers by only spaces the user has access to
- [x] Ability to add new people to the private space
- [x] Ability to create public and private spaces on UI (separate buttons, checkbox in the dialog?)

**Comment by haiodo** [comment]
This is done.
