### ISSUE TITLE
Workbench

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#122]
`Workbench` -- рабочая область платформы. Детали рабочей области задаются перспективой (`Perspective`). Перспектива определяет какие объекты присутствуют на экране. 

> Почему перспектива а не, например, приложение? Перспектива может включать в себя компоненты предоставляемые разными приложениями (производителями). Так же пользователь может создавать свои, удобные ему перспективы для работы с платформой.

Как это выглядит сейчас:

<img width="1057" alt="Screen Shot 2020-09-25 at 9 50 39 AM" src="https://user-images.githubusercontent.com/57532613/94241892-9193cc80-ff15-11ea-8b0c-e7caab77df3a.png">

**Comment by haiodo** [comment]
Seems done.
