### ISSUE TITLE
Application: Activity

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#126]
Приложение показывает все изменения произошедшие в данном пространстве в хронологическом порядке. Сейчас так:

<img width="901" alt="Screen Shot 2020-09-25 at 12 40 26 PM" src="https://user-images.githubusercontent.com/57532613/94257901-4cc76000-ff2c-11ea-9d78-744a5d11e7b6.png">

Хочется чего то поинтереснее с разными иконками на каждый тип события и как то возможно их визуально соединить чтобы было ощущение потока :)

**Comment by haiodo** [comment]
+ Возможны какие то группировки, и выделение того что пользователь уже видел.

Я думаю что допустимы пересортировки в случае большого количества изменений одного и того же объекта в случае если текущий пользователь не видел их все.
