### ISSUE TITLE
Create New Object

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#131]
Сейчас новый объект создается в модальном диалоге, открываемом кнопкой (+) в заголовке приложения:

<img width="937" alt="Screen Shot 2020-09-25 at 6 26 27 PM" src="https://user-images.githubusercontent.com/57532613/94292049-ba8b8000-ff5c-11ea-9503-0dd7f8f898e3.png">

**Comment by haiodo** [comment]
+  Хотелось бы как то разделить Cancel и возможность создавать Draft
? возможно стоит как минимум запоминать введенные значения в случае закрытия окна по on blur или по Cancel.
