### ISSUE TITLE
Comments are not displayed correctly in table

### ISSUE THREAD

**Issue by artyom-savchenko** [anticrm/platform#260]
![Screen Shot 2021-02-28 at 18 20 25](https://user-images.githubusercontent.com/79742701/109418221-cabaf600-79f9-11eb-8345-82c12028fdde.png)

The string representation is used for comments and it doesn't work.
Should a separate presenter be added for arrays?

**Comment by z2sx** [comment]
We have a concept of Presenters/Editors. Platform should use appropriate `Presenter` to display array of comments.

**Comment by haiodo** [comment]
Right now we could define Presenter only for class, we need a way to define a presenter to ArrayOf<Class>

**Comment by artyom-savchenko** [comment]
Yes, actually I have already added a new presenter and associated with 'ArrayOf ' type. I am currently in progress with some integration issues

**Comment by artyom-savchenko** [comment]
It has been fixed in this PR: https://github.com/anticrm/platform/pull/263
