### ISSUE TITLE
Replace `Platform.getRunningPlugin(id)` uses with safe `getPlugin(id)`

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#278]
I believe it's safe to use this method in many places we use it now, the question is can we avoid or even remove this method in favor of safe `Platform.getPlugin(id)`?

**Comment by haiodo** [comment]
Yes, I think we could to have only Platform.getPlugin(id)

**Comment by z2sx** [comment]
OK, renaming this to fix `getRunningPlugin` usages :)

**Comment by haiodo** [comment]
This is done.
