### ISSUE TITLE
Business Object form look and feel

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#31]
We have to design a "standard" business object (editing) form. Here is a current example of the form design:

<img width="653" alt="Screen Shot 2020-06-15 at 3 10 33 PM" src="https://user-images.githubusercontent.com/57532613/84661467-af1ac880-af1a-11ea-8332-66debc4cffc1.png">

To simplify things here, every object belongs to number of classes, each class have a number of attributes. For example an object of `Employee` class may have following attributes:
* `Date-of-Employment` from `Employee` class.
* `Birthday` from `Person` class.
* `Phone` and `Email` from `Contact` class.

Also, attribute value is of some `type`. For example `Home Phone` and `Work Phone` are of type `Phone`, while `Email 2` is of type `Email`.

Let's work on standard object form look and feel here. Questions so far:
* Where we should put `Business Object` information? Currently it's `Created On`, `Created By` and we will add more shortly.
* Overall design ideas?

**Comment by am35a** [comment]
this is a profile card, may be it will look like a driver's license...
Place on the left side a photo in full height. on the right use list items, according to the hierarchy, display user data. wraping card in one font and headers style will be good
