### ISSUE TITLE
Table control

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#329]
We need table control capable to show any objects (including mixins). User should be able to customize view (exclude and reorder columns, etc).

**Comment by LoinASD** [comment]
This table is designed to be fully reactive, customazible and has the following features:

- [ x ] Sorting by column (requires core `Comparer` for correct sorting by non-primitive types)
- [ x ] Filtering (searching) (the same story with comparer) 
- [ x ] Pagination (only render pagination for now, without query logic)
- [ ] Column ordering
- [ ] Column visibility
- [ ] mixed attributes
- [ ] Pagination: go to <number> page input - allow us to jump onto chosen page

Feel free to add any features
