### ISSUE TITLE
CreateTx and UpdateTx should be filtered by _space of object.

### ISSUE THREAD

**Issue by haiodo** [anticrm/platform#398]
Right now we have a security hole, since it is possible to fetch a all create transactions and they will contain objects from not available space.

**Comment by z2sx** [comment]
Sounds good if we maintain a list of permitted spaces for a client.

**Comment by haiodo** [comment]
Yes, we maintain while it had a live websocket connection.

**Comment by haiodo** [comment]
Most questionable here is ability to move object from one space to another, 
since transactions like create and update should be available to another space in this case. 

Maybe we should have some transaction kind, 
```typescript
interface SpaceMoveTx extends Tx {
   _objectId: Ref<Doc> // A source object Id
   _targetId: Ref<Doc> // A target object Id.
   _objectClass: Ref<Class<Doc>>
  _sourceSpace: Ref<Space> // Source space
  _targetSpace: Ref<Space> // Target space
  _operationTime: Date // A time then occur, since we could move it back again :-)
  _object: AnyLayout // A final object state after it was moved, assume move operation do some changes, like title, assignee etc.
}
```

So after we do move, object will look like deleted for _sourceSpace owners and we have a new transaction for new space and object will be accessible to it.

Thoughts?

**Comment by z2sx** [comment]
What is `_targetId`?

**Comment by z2sx** [comment]
How security works now if we don't have `space` in CreateTx, UpdateTx, DeleteTx?

**Comment by haiodo** [comment]
_targetId is not required, security is not working for Tx, etc.

Right now to support query objects without spaces, null was added to query for mongo.

Like
```db.getCollection('tx').find({_space: {$in: [null]}})```
So in case there is no field _space, all objects are returned.

**Comment by z2sx** [comment]
`_operationTime`: do not we have something similar in base `Tx` class?

**Comment by z2sx** [comment]
> db.getCollection('tx').find({_space: {$in: [null]}})

So we already have `space` information in `Tx`?

**Comment by haiodo** [comment]
Yes, we have _date in Tx :-) We do not have space in Tx right now.

**Comment by z2sx** [comment]
So, finally, let's add `_objectSpace` to relevant Txes. Let's postpone `move` operation.
