### ISSUE TITLE
extendsOfClass returns class extends and the class itself 

### ISSUE THREAD

**Issue by BykhovDenis** [anticrm/platform#424]
extendsOfClass returns class extends and the class itself. I think it must return only extends, or maybe it must has additional parameter as flag.

**Comment by haiodo** [comment]
It is by construction since it builds a map by traversing getClassHierarchy() results and it return class and it's parent classes.

Also I've used it like all classes what implements _class. So itself is also used.

We could have a separate public methods in case it will be required.
