### ISSUE TITLE
Implement conversation channels (groups, chats)

### ISSUE THREAD

**Issue by kevromster** [anticrm/platform#93]
As a user, I want to communicate with other users in a common chat in order to share information or discuss something.
- [x] Button to create a new channel
- [x] Link to the channel from the main page (maybe list of channels?)
- [ ] Ability to invite users to the channel (or at least an invitation link)
- [ ] Support of pictures sharing in the channel
- [ ] Support of files sharing in the channel
- [ ] Support of code blocks sharing in the channel
- [ ] Ability to restrict who can participate in the conversation by channel creator

**Comment by haiodo** [comment]
Question here is how Space concept are merged with Channels, 
As discussed before it is probable it should be ok to have just one channel per project, 
but probable a few channels per project are also ok.

**Comment by kevromster** [comment]
One channel per project can be implemented first in MVP (if it is simpler), but later I think we need multiple channels because users may want to discuss different logical things in different channels (and this is very convenient in Slack :) ).

**Comment by haiodo** [comment]
> One channel per project can be implemented first in MVP (if it is simpler), but later I think we need multiple channels because users may want to discuss different logical things in different channels (and this is very convenient in Slack :) ).

In slack you have only channels, not spaces, we could have multiple channels inside space I suppose and they will share same object space, so it should be ok. 

Question is only for direct(group) messages, should they be out of space or be inside space, both variables are possible:
1. Inside space, allow to assume conversation are related to space and if user will be rejected from space it will loose it.
2. Outside space will not be able to access object space for references, etc.

**Comment by kevromster** [comment]
I would prefer variant 1, conversations are restricted by its space, otherwise space is not space :)

**Comment by haiodo** [comment]
> I would prefer variant 1, conversations are restricted by its space, otherwise space is not space :)

When direct messages became not so clear for end users, so we need to be careful.

**Comment by z2sx** [comment]
So we're going with multiple chat channels per space?

**Comment by z2sx** [comment]
OK, if we go with multiple chats per space, we have to go with multiple `lists` of other objects, e.g. `candidates` is this what we want to have?

**Comment by kevromster** [comment]
After discussions:
- Let's treat `space` as a communication channel with all its data and access rights defined.
- Spaces might have different views, one of them is `chat`.
- Spaces can be switched from the left bar.
- Any user can create a new space (need button for it) to open a new conversation channel.

**Comment by kevromster** [comment]
To support restriction functionality, we first need to implement secure spaces, see issue #112.

**Comment by haiodo** [comment]
Not relevant right now. Closing.
