### ISSUE TITLE
Implement p2p conversation channels

### ISSUE THREAD

**Issue by kevromster** [anticrm/platform#94]
As a user, I need a private conversation channel with another user in order to communicate directly.
- [ ] The same channel functionality as in #93 
- [ ] Nobody except two communicating users can see/participate in the conversation

**Comment by haiodo** [comment]
@kevromster Why we need to distinguish? a Channel has a list of members and they could communicate, this one is just a one to one variant. I propose have just one issue.

**Comment by kevromster** [comment]
How will we restrict who can communicate? By default (I assumed) channels are open to everyone, so such restriction is additional feature :)

**Comment by haiodo** [comment]
p2p channels are closed by nature, not see any difference to have private group channels in first version.

**Comment by haiodo** [comment]
Also in slack it is possible to invite person to p2p discussion.

**Comment by kevromster** [comment]
Ok, let's add restriction as a requirement into the previous issue and close this one.

**Comment by kevromster** [comment]
Closed as a duplicate of #93
