### ISSUE TITLE
On Spaces and Lists

### ISSUE THREAD

**Issue by z2sx** [anticrm/platform#97]
`Space` is a unit which controls permissions to deal with objects living in a space. User may have or have no access to a space. Additional security mechanism within space may be enforced. Space is a place for multiple lists.

A List define types of objects which may contain in the list as well as customize other parameters shared by all objects within a list. So we may have typed lists 'Client Tasks' or 'Server Tasks' containing `Task` objects. Or 'Meeting minutes' list containing `Page` objects.

So we have `Space` -> `List` -> `Object` hierarchy, where `Space` serves security purposes and `Lists` for information organization purposes.

This is follow on #93

**Comment by z2sx** [comment]
'List' is also a kind of parametrization for the list's type. For example a `Task` list may define task kinds or possible tasks status values.

**Comment by z2sx** [comment]
The only 'disadvantage' of this model is in-place object (such as `Page`) creation. So when we mention inexistent page in the chat like ```Our partner [[ACME Corp]]```, we can't create page immediately. On the another side, this 'disadvantage' leads to nice workflow: we show a link on inexistent page (maybe accompanied with `Create` icon), and ask for additional information on click (such as `List` where create the object, which also implies type of the object to be created). So this will lead to very fast tasks creation from 'meeting notes' as an example.

**Comment by kevromster** [comment]
It looks like a classical hierarchy of objects: I would say that `List` may contain another `List` inside (for example, 'Client tasks' with two sublists with statuses 'Done' and 'InProgress').
An alternative approach is to introduce some labels and to filter objects within space by these labels. 'Meeting minutes' docs will have such label applied.

> when we mention inexistent page in the chat like `Our partner [[ACME Corp]]`, we can't create page immediately.

Yes, this is not very good: If I enter some text in doubled square brackets, then I do want to create a page. But we also may consider approach when the user selects some text in the previously entered message and creates a page from it via the context menu.

**Comment by haiodo** [comment]
This is not required at this moment so closing.
